### ISSUE TITLE
Error encountered installing on Apple M1 Mac

### ISSUE THREAD

**Issue by kerchner** [omicsEye/deepbreaks#2]
Following the  instructions led to the following error when executing the [Apple M1 Mac instructions](https://github.com/omicsEye/deepbreaks/tree/61c793d70dad6a4c52424691ef6801a51c3f5493#apple-m1-mac), at the last step (`python -m pip install git+https://github.com/omicsEye/deepbreaks`).  This prevented successful installation of `deepBreaks`.

System info:
- MacOS Monterey 12.5
- MacBook Pro, 2021
- Apple M1 Pro chip
- Memory 32 GB

```
INFO: pip is looking at multiple versions of boruta to determine which version is compatible with other requirements. This could take a while.
Collecting Boruta
  Downloading Boruta-0.2.2-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 kB 1.9 MB/s eta 0:00:00
  Downloading Boruta-0.2.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 1.9 MB/s eta 0:00:00
  Downloading Boruta-0.2.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 2.0 MB/s eta 0:00:00
  Downloading Boruta-0.1.5.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.4.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.3.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cy/w1jkfhn93t92fslvgkhzst4c0000gq/T/pip-install-5pvffo_u/boruta_467a7b517fb345268e927a92c808b0df/setup.py", line 3, in <module>
          setup(name='Boruta',
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/Users/kerchner/opt/anaconda3/envs/deepBreaks_env/lib/python3.8/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/cy/w1jkfhn93t92fslvgkhzst4c0000gq/T/pip-install-5pvffo_u/boruta_467a7b517fb345268e927a92c808b0df/.eggs/setuptools_markdown-0.4.1-py3.8.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mahdibaghbanzadeh** [comment]
I using this useful [link](https://bobbyhadz.com/blog/python-note-this-error-originates-from-subprocess):

1. Upgrade your versions of `pip`, `setuptools` and `wheel`.

- `pip install wheel setuptools pip --upgrade`
2. If that doesn't solve the issue, then add `--use-deprecated=legacy-resolver` to the end of `pip` command:
- `python -m pip install git+https://github.com/omicsEye/deepbreaks --use-deprecated=legacy-resolver`

**Comment by kerchner** [comment]
Thank you @mahdibaghbanzadeh, adding `--use-deprecated=legacy-resolver` resulted in a successful install. 😃 

For what it's worth, my `pip` is now at version 22.3.1.

I am not sure but you may consider whether a more detailed `requirements.txt` might avoid this issue for people.  Here is what my `pip freeze` returns, although there is probably a lot of extra junk in there (libraries not used by deepBreaks) due to building off `conda`'s base environment:

```
adagio==0.2.4
aiohttp==3.8.3
aiosignal==1.3.1
alembic==1.8.1
ansi2html==1.8.0
antlr4-python3-runtime==4.11.1
anyio==3.6.2
appdirs==1.4.4
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.1.0
autopage==0.5.1
autoviz==0.1.58
azure-core==1.26.1
azure-storage-blob==12.14.1
backcall==0.2.0
bcrypt==4.0.1
beautifulsoup4==4.11.1
bleach==5.0.1
blis==0.7.9
bokeh==3.0.3
Boruta==0.3
boto3==1.26.29
botocore==1.29.29
Brotli==1.0.9
cachetools==5.2.0
catalogue==1.0.2
catboost==1.1.1
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0ek9yztvu3/croot/certifi_1665076692562/work/certifi
cffi==1.15.1
charset-normalizer==2.1.1
chart-studio==1.1.0
click==8.1.3
cliff==4.1.0
cloudpickle==2.2.0
cmaes==0.9.0
cmd2==2.4.2
colorcet==3.0.1
colorlog==6.7.0
colorlover==0.3.0
colour==0.1.5
comm==0.1.2
contourpy==1.0.6
cryptography==38.0.4
cufflinks==0.17.3
cycler==0.11.0
cymem==2.0.7
dash==2.7.1
dash-auth==1.4.1
dash-bootstrap-components==1.2.1
dash-core-components==2.0.0
dash-cytoscape==0.3.0
dash-html-components==2.0.0
dash-table==5.0.0
databricks-cli==0.17.4
dataclasses==0.6
debugpy==1.6.4
decorator==5.1.1
deepBreaks @ git+https://github.com/omicsEye/deepbreaks@61c793d70dad6a4c52424691ef6801a51c3f5493
defusedxml==0.7.1
dill==0.3.6
distlib==0.3.6
docker==6.0.1
dtreeviz==1.4.1
emoji==2.2.0
entrypoints==0.4
evidently==0.2.1
exceptiongroup==1.0.4
executing==1.2.0
explainerdashboard==0.4.0
fairlearn==0.8.0
fastapi==0.88.0
fastjsonschema==2.16.2
ffmpy==0.3.0
filelock==3.8.2
Flask==2.2.2
Flask-Compress==1.13
Flask-SeaSurf==1.1.1
flask-simplelogin==0.1.1
Flask-WTF==0.15.1
fonttools==4.38.0
frozenlist==1.3.3
fs==2.4.16
fsspec==2022.11.0
fugue==0.7.3
fugue-sql-antlr==0.1.1
funcy==1.17
future==0.18.2
gensim==3.8.3
gevent==22.10.2
gitdb==4.0.10
GitPython==3.1.29
google-api-core==2.11.0
google-auth==2.15.0
google-cloud-core==2.3.2
google-cloud-storage==2.7.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
gradio==3.13.0
graphviz==0.20.1
greenlet==2.0.1
grpcio==1.51.1
gunicorn==20.1.0
h11==0.14.0
holoviews==1.15.3
htmlmin==0.1.12
httpcore==0.16.2
httpx==0.23.1
hvplot==0.8.2
hyperopt==0.2.7
idna==3.4
ImageHash==4.3.1
imageio==2.22.4
imbalanced-learn==0.7.0
importlib-metadata==5.1.0
importlib-resources==5.10.1
iniconfig==1.1.1
interpret==0.2.4
interpret-core==0.3.0
ipykernel==6.19.2
ipython==8.7.0
ipython-genutils==0.2.0
ipywidgets==8.0.3
isodate==0.6.1
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
jmespath==1.0.1
joblib @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_955tow_ysb/croot/joblib_1666298851241/work
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-dash==0.4.2
jupyter-events==0.5.0
jupyter_client==7.4.8
jupyter_core==5.1.0
jupyter_server==2.0.1
jupyter_server_terminals==0.4.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.4
kiwisolver==1.4.4
kmodes==0.12.2
lightgbm @ file:///opt/concourse/worker/volumes/live/d806a261-7af6-49f5-5980-5849606af2f6/volume/lightgbm_1633019194754/work
lime==0.2.0.1
linkify-it-py==1.0.3
llvmlite==0.37.0
m2cgen==0.10.0
Mako==1.2.4
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
mistune==2.0.4
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/f196a661-8e33-4aac-63bc-efb2ff50e035/volume/mkl_random_1626186080069/work
mkl-service==2.4.0
mlflow==2.0.1
mlxtend==0.21.0
msgpack==1.0.4
msrest==0.7.1
multidict==6.0.3
multimethod==1.9
multiprocess==0.70.14
murmurhash==1.0.9
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.6
nbformat==5.7.0
nest-asyncio==1.5.6
networkx==2.8.8
nltk==3.8
notebook==6.5.2
notebook_shim==0.2.2
numba==0.54.1
numexpr==2.8.4
numpy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cd2y6umv2d/croot/numpy_and_numpy_base_1668593733683/work
oauthlib==3.2.2
optuna==3.0.4
orjson==3.8.3
oyaml==1.0
packaging==21.3
pandas==1.5.2
pandas-profiling==3.5.0
pandocfilters==1.5.0
panel==0.12.7
param==1.12.3
paramiko==2.12.0
parso==0.8.3
patsy==0.5.3
pbr==5.11.0
pexpect==4.8.0
phik==0.12.3
pickleshare==0.7.5
Pillow==9.3.0
pkgutil_resolve_name==1.3.10
plac==1.1.3
platformdirs==2.6.0
plotly==5.11.0
pluggy==1.0.0
preshed==3.0.8
prettytable==3.5.0
prometheus-client==0.15.0
prompt-toolkit==3.0.36
protobuf==4.21.12
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py4j==0.10.9.7
pyamg==4.2.3
pyaml==21.10.1
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycaret==2.3.10
pycparser==2.21
pycryptodome==3.16.0
pyct==0.4.8
pydantic==1.10.2
pydub==0.25.1
Pygments==2.13.0
PyJWT==2.6.0
pyLDAvis==3.3.1
PyNaCl==1.5.0
pynndescent==0.5.8
pyod==1.0.6
pyparsing==3.0.9
pyperclip==1.8.2
pyrsistent==0.19.2
pytest==7.2.0
python-dateutil==2.8.2
python-json-logger==2.0.4
python-multipart==0.0.5
pytz==2022.6
pyviz-comms==2.2.1
PyWavelets==1.4.1
PyYAML==5.4.1
pyzmq==24.0.1
qpd==0.3.3
qtconsole==5.4.0
QtPy==2.3.0
querystring-parser==1.2.4
ray==2.2.0
regex==2022.10.31
requests==2.28.1
requests-oauthlib==1.3.1
retrying==1.3.4
rfc3986==1.5.0
rsa==4.9
s3transfer==0.6.0
SALib==1.4.6.1
scikit-image==0.19.3
scikit-learn @ file:///opt/concourse/worker/volumes/live/111833a2-339b-4578-413b-7337bb8fe64a/volume/scikit-learn_1598376920601/work
scikit-optimize==0.9.0
scikit-plot==0.3.7
scipy==1.5.4
seaborn==0.12.1
Send2Trash==1.8.0
shap==0.41.0
six @ file:///tmp/build/80754af9/six_1644875935023/work
sklearn==0.0.post1
skope-rules==1.0.1
slicer==0.0.7
smart-open==6.3.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
spacy==2.3.8
SQLAlchemy==1.4.45
sqlparse==0.4.3
srsly==1.0.6
stack-data==0.6.2
starlette==0.22.0
statsmodels==0.13.5
stevedore==4.1.1
tabulate==0.9.0
tangled-up-in-unicode==0.2.0
tenacity==8.1.0
tensorboardX==2.5.1
terminado==0.17.1
textblob==0.17.1
thinc==7.4.6
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
tifffile==2022.10.10
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
traitlets==5.7.1
treeinterpreter==0.2.3
triad==0.7.0
tune-sklearn==0.4.5
typeguard==2.13.3
typing_extensions==4.4.0
ua-parser==0.16.1
uc-micro-py==1.0.1
umap-learn==0.5.3
urllib3==1.26.13
uvicorn==0.20.0
virtualenv==20.17.1
visions==0.7.5
waitress==2.1.2
wasabi==0.10.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
websockets==10.4
Werkzeug==2.2.2
widgetsnbextension==4.0.4
wordcloud==1.8.2.2
WTForms==3.0.1
xgboost==1.7.2
xlrd==2.0.1
xyzservices==2022.9.0
yarl==1.8.2
yellowbrick==1.5
zipp==3.11.0
zope.event==4.5.0
zope.interface==5.5.2
```
